title: The SSJS Framework
description: Framework that creates a sfmc compatible script from modern Javascript. 
theme: just-the-docs

search_enabled: true
color_scheme: ssjs

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: yellow

